# GitHub Pages Configuration
theme: null
plugins: []
source: .
destination: ./_site
include:
  - index.html
  - additional-projects.html
  - "*.html"
  - "*.css"
  - "*.js"
  - rf-power-amplifier-5g6g
  - portfolio-showcase
exclude:
  - node_modules
  - .git
baseurl: "/louis-antoine-portfolio"
url: "https://alovladi007.github.io"